### ISSUE TITLE
Cannot bundle express.d.ts references

### ISSUE THREAD

**Issue by pgrm** [TypeStrong/dts-bundle#16]
in the current version of [express.d.ts](https://github.com/borisyankov/DefinitelyTyped/blob/master/express/express.d.ts) is the following code block:

    /* =================== USAGE ===================
        import express = require('express');
        var app = express();
     =============================================== */

because the end of a comment is detected with the following regex: `/^[ \t]*\*+\/` it means that dts-bundle never detects the end of the comment and thinks, the whole files is commented out.

**Comment by poelstra** [comment]
@pgrm Note that progress is being made on creating a solution that works out-of-the-box. See e.g. #2338, #2839. In the mean time, it may be interesting to look at https://github.com/SitePen/dts-generator, as it doesn't use regexes for creating the bundles and is more recently updated.

**Comment by pgrm** [comment]
The typescript issues are, where I've found this repository in the first place, for now I've just put a new line before the end of the comment and that works, but I'll also try dts-generator, thx
