### ISSUE TITLE
please add me to owner of npm

### ISSUE THREAD

**Issue by vvakame** [TypeStrong/dts-bundle#21]
please add me to owner of npm. I want publish to npm.
@Bartvds @basarat Who can do it?
`npm owner add vvakame dts-bundle`

**Comment by basarat** [comment]
Only @Bartvds  🌹

**Comment by vvakame** [comment]
umm... and same as grunt-dts-bundle.

**Comment by Bartvds** [comment]
Sorry for late reaction; I'm completely out of the loop on Open Source and Github.

I'll try to arrange this tonight; feel free to spam/remind me at my @gmail adress (you both have it) if you have issues with my stuff.

**Comment by Bartvds** [comment]
:snail: :-1:  Sorry, both done now.

**Comment by vvakame** [comment]
wow, thanks! :smile_cat:
