### ISSUE TITLE
CLI tests not passed on travis

### ISSUE THREAD

**Issue by tolemac** [TypeStrong/dts-bundle#31]
The test doesn't pass because needs to `npm install -g dts-bundle` and travis dont found `dts-bundle` command.

I have added this:

````
before_script:
  - npm install -g
````

to `.travis.yml` but doesn't work ...
I can't install via `npm install -g dts-bundle` because the published npm package don't have the CLI feature ...

Need help about that :octopus: 
@basarat :sos: ;)

**Comment by basarat** [comment]
> I can't install via npm install -g dts-bundle because the published npm package don't have the CLI feature ... 

Don't go `npm install -g` on test env. Just do `require('child_process').exec` `"node ./path/to/cli/tool"`  in the test env

**Comment by tolemac** [comment]
Done!!
Thank you very much!
