### ISSUE TITLE
Consider optional "name" setting

### ISSUE THREAD

**Issue by tsv2013** [TypeStrong/dts-bundle#34]
If "name" option is not defined, dts-bundle does not wrap output with module definition:

instead of 
```
// Generated by dts-bundle v0.4.3

declare module 'MyBundle' {
    module Module1 {
        function validateGuid(guid: any): boolean;
    }
    module Module2 {
        function validateGuid(guid: any): boolean;
    }
}    
```
generate just

```
// Generated by dts-bundle v0.4.3

module Module1 {
    function validateGuid(guid: any): boolean;
}
module Module2 {
    function validateGuid(guid: any): boolean;
}
```

**Comment by tolemac** [comment]
Can you explain me a case of use where you need it?

Thanks.

**Comment by tsv2013** [comment]
Now I feel like I've used wrong tool. I have a set of .ts file with internal modules. I combine them into a single resulting file, say "result.ts". I'd like to create a single corresponding "result.d.ts" file. And, in the "result.d.ts" I need no references ("/// <reference path=...") completely as well as simply combine internal modules.

I've been expected "dts-bundle" as a tool for solving my tasks. May be I was wrong, and this is not your scenario. In this case you can simply close this issue.

Thanks

**Comment by tolemac** [comment]
Yes, this is not the scenario of dts-bundle.

When I need it I usually create "result.ts" file manually exporting the others modules. I usually have a "result.ts" file for each folder, see this example https://github.com/tolemac/ngts/blob/master/ngts.ts

It's exporting "decorators/decorators" and this is the code that module https://github.com/tolemac/ngts/blob/master/decorators.ts
