### ISSUE TITLE
bundler fails when files are imported by directory name (CommonJS idiom)

### ISSUE THREAD

**Issue by bjouhier** [TypeStrong/dts-bundle#38]
My main `.d.ts` file contained a line like:
```js
// ./foo is subdirectory containing an `index.d.ts` file
import * as foo from './foo'; 
```
 This failed. I fixed it by replacing `./foo` by `./foo/index`.

**Comment by tolemac** [comment]
Do you mean to the original .d.ts file? generated by tsc ??

Can you paste here the error output?

Thanks.

**Comment by tolemac** [comment]
@bjouhier can you help me to reproduce the problem?

**Comment by kcjmowright** [comment]
I have a fix for this.  See https://github.com/TypeStrong/dts-bundle/pull/40

**Comment by kcjmowright** [comment]
I finally have the right fix for this with a test.

See https://github.com/TypeStrong/dts-bundle/pull/42

**Comment by thefabulousdev** [comment]
As the repository contributors seem to be absent I have created a fork of the package with the pending PR which solves this merged. 

Just replace npm `dts-bundle` package by `dts-bundle-hot-fix` .

**Comment by tolemac** [comment]
I will take a look to it the nexts days.

**Comment by tolemac** [comment]
0.6.0 npm version released.
Thanks!
