### ISSUE TITLE
Switch to default no prefix?

### ISSUE THREAD

**Issue by Bartvds** [TypeStrong/dts-bundle#4]
Maybe set `prefix` to empty string by default? 

Not sure, but I think that would still be valid and sensible, as many modules use submodules that look like a path (eg: without leading dots/slash).

I originally had '__' to make the sub modules look 'private' but maybe that's not really necessary.

So this:

````ts
declare module 'foo/bar' {}
````
Instead of:

````ts
declare module '__foo/bar' {}
````

@poelstra What do you think?

**Comment by tolemac** [comment]
What about this?

I use `prefix = ""` always ...

If nobody says anything I proceed to change it.
