### ISSUE TITLE
wrong parameter for "All .d.ts files" feature

### ISSUE THREAD

**Issue by donpark** [TypeStrong/dts-bundle#43]
Instruction under **All .d.ts files** section of README.md states `name` parameter should be used:

> If you set **name** parameter to some path ended with **/*.d.ts then dts-bundle load all .d.ts files and generate a bundle.

I was able to enable this feature using `main` but not `name` parameter. Shouldn't this be `main` parameter?

**Comment by tolemac** [comment]
Fixed!
