### ISSUE TITLE
Doesn't work on macOS X

### ISSUE THREAD

**Issue by vp2177** [TypeStrong/dts-bundle#44]
Looks like #33 is still present:

`env: node\r: No such file or directory`

Using `dts-bundle@0.6.0`

**Comment by origin1tech** [comment]
Install dos2unix

    brew install dos2unix

Then run against lib files where your node config prefix is located at /var/local

    dos2unix /var/local/lib/node_modules/dts-bundle/lib/index.js
 
Do the same for the dts-bundle.js file at the same path. 

To check your node prefix run

    npm config get prefix

**Comment by tolemac** [comment]
Its a problem with line ending.
I'm going to fix it.

**Comment by origin1tech** [comment]
@tolemac just patched it up real quick as I needed it tonight but yeah that's all it is...

**Comment by tolemac** [comment]
@vp2177 I have just released 0.6.1 version.

Can you test it? I'm over windows system now.

**Comment by origin1tech** [comment]
yeah sure..just a sec.

**Comment by origin1tech** [comment]
Yep all good!!! 💯

**Comment by tolemac** [comment]
Sorry for that, It isn't the first time. I work under windows and Git change the line endings on checkout, later npm publish upload files with CRLF to npm server and only git push change the line endings when upload to git server.

I have added `.gitattributes` file where assign LF line ending to TS and JS files ... I hope that will be the last time.
