### ISSUE TITLE
file not found error if both .d.ts file and a folder with the same name exist

### ISSUE THREAD

**Issue by djflex68** [TypeStrong/dts-bundle#51]
Hello,

I run into an issue, using the following command :
`dts-bundle --name myApp --main dts/**/*.d.ts --out bundle.d.ts`

in dts folder, I have both a file called application.d.ts and a folder application.
I get the following error, and don't know how to solve it (excepted by renaming the folder or the file) :

```
Error: ENOENT: no such file or directory, open 'D:\(...)\dts\application\index.d.ts'

```

Thanks !

**Comment by esugoi** [comment]
I'm having this same problem.
Indeed, renaming the folder or file resolves the problem. But this is not an option when bundling third party dts files.

**Comment by tolemac** [comment]
Sorry about that, I have no much free time lately, and I'm involved in others projects, ...
In addition I have stopped using "dts-bundle" in personal projects 1 year ago, I think is not needed currently. 

Can you make a pull request with the solution?

**Comment by djflex68** [comment]
Thanks for your answer.
Personally, I haven't found a better solution than using your plugin to bundle all definition files into a single one. It's the only way to expose and consume easily classes accross several modules, without having to hand-create a huge hierarchy of definition files. But maybe you found something better in the meantime ?  
That said, I'm not sure what the solution is, but I suspect that at line 587, you just check if the file is a directory, but you should probably also test that there is no file with the same name.
What do you think about this ?

**Comment by esugoi** [comment]
No need to apologize, @tolemac , this is an open project. Thanks a lot for your time spent here. ;)
I don't have much time available too, but I'll try to take a look when possible. Thanks.

**Comment by tolemac** [comment]
@esugoi the slowest part is to build a test case ... :(

@djflex68 Most of projects used to distribute several `.d.ts` files, Angular for example, you can take a look to my project [tolefocus](https://github.com/tolemac/ToleFocus) where I distribute .d.ts and .js files and is easy to use from npm.

**Comment by tolemac** [comment]
I have merged the pull request by @esugoi that fixes it.
If you have any problem tell me here.

Best regards!

**Comment by esugoi** [comment]
Glad I could help. :)
In my case I bundled dts files of the angular project and it worked like a charm. ;)
Thanks for your work, @tolemac .

**Comment by elsasslegend** [comment]
Many thanks @esugoi and @tolemac for the work and help :-)
